### ISSUE TITLE
Golang Dependency Missing

### ISSUE THREAD

**Issue by zwerch** [bahlo/dotfiles#1]
First things first, thanks a lot for your awesome dotfiles, I'm using almost all of them and almost all of your settings, they're great! :heart:

I got a new computer recently and wanted a fresh start. I installed your dotfiles and it worked well, but I encountered an error while installing the `vim-plugins` part because apparently a plugin needs `golang` to be installed. `brew install golang` solved the issue.

Maybe you could add it to the `Brewfile`?

**Comment by bahlo** [comment]
Thanks for the suggestion, done in 1040df1.
